### ISSUE TITLE
Requirements for it to work.

### ISSUE THREAD

**Issue by rafamerlin** [bauca/graphics-switcher#1]
Hey, just saw this on http://askubuntu.com/questions/667466/screen-tearing-in-ubuntu-with-nvidia-intel-graphics

I'm trying this on Ubuntu Mate 16. Do I still need to install bumblebee?

Thanks a lot.

**Comment by bauca** [comment]
Hi Merurino, thanks for your question,
Bumblebee is not required, but you will still need to install nvidia drivers and nvidia prime. If you have any further question, feel free to ask.

Regards,
Bruno.

**Comment by bauca** [comment]
I've updated the list of requirements, please feel  free to collaborate if you see that I've missed anything.
