### ISSUE TITLE
glxinfo is not installed

### ISSUE THREAD

**Issue by ekulabuhov** [bauca/graphics-switcher#2]
Not sure if it's supposed to be installed with Ubuntu 16.04. Would be nice to have a list of requirements needed to run this script. Thanks!

**Comment by bauca** [comment]
Hi ekulabuhov, thanks for your feedback, I am planning to do some improvements to this script next month (08/2017). I will do my best to release a complete list of requirements.

**Comment by bauca** [comment]
I've updated the list of requirements, please feel free to collaborate if you see that I missed anything.
