### ISSUE TITLE
Black screen?

### ISSUE THREAD

**Issue by ruffson** [bauca/graphics-switcher#3]
I am using Ubuntu 16.04 and followed this answer to solve the tearing: https://askubuntu.com/questions/667466/screen-tearing-in-ubuntu-with-nvidia-intel-graphics/668590#668590?newreg=f53f418593a44d57b4e528ea89b4fc23

So I put this snippet 
```
Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
   Option      "TearFree"    "true"
EndSection
```
in `/usr/share/X11/xorg.conf.d/20-intel.conf` 

And the tearing under Intel graphics (in my case HD 4000) was gone.
However with this setup, I couldn't boot with nvidia activated. I was presented with a black screen instead of the lightdm login screen.
This caused a lot of frustration and me installing a bunch of nvidia drivers because I didn't think that this script was the problem.

My question is: will your script be different? Do you know about this bug? Is there a `revert` option that enables me to go back after? And is there a way to include this into the prime indicator plus applet?

**Comment by bauca** [comment]
Hi ruffson, I am sorry to hear that it didn't work as expected to you. But as far as I can see, the problem is that the file '20-intel.conf' wasn't deleted after switching back to NVIDIA's. Black screen will happen if the file still remain in the folder '/etc/X11/'. I noticed that your folder is different, I don't know why it is different, but I will figure out. Next week I will be on vacation, so I will dedicate some time to fix it and make some improvements. I see that you forked and updated the folder, did it work well to your videocard (Intel HD 4000)? Thanks for your feedback.

**Comment by ruffson** [comment]
Hi bauca, thanks so much for your comprehensive answer.

So I ran your script yesterday with only changing the "Geforce" specifier to fit my graphics card (Quadro K200M). After rebooting however, I couldn't log in so I deleted the generated conf files.

On my system (Ubuntu 16.04 with Budgie) the `xorg.conf.d`folder is not in `/etc/X11/` but in `/usr/share/X11/´ I think that was changed (it was also mentioned in the link I provided up there).
So I went ahead and changed your script (as you can see from my fork) and changed the folder.

Switching back and forth worked fine initially. But at some point after running it (maybe with wrong) permissions) I ended up with a state where I couldn't log in and also get errors when switching back to intel. I can not check right now but from memory it now tells me that modbus.d is not a folder or file and also the "intel" specifier is available in prime-select. When I switch to intel it tells me that there is only two nvivia drivers available but no intel. Now I tried to reinstall xorg stuff and purged intel and nvidia but still after installing the drivers it is still messed up. I don't know enough about the X11 to know how to fix this.
But I guess (or rather hope) that this comes down to defining the right xorg conf files in the right folders.
I will try to properly purge all the xorg, nvidia, intel things and reinstall. Hopefully that will bring be back to a working state.
The very first time when I created the 20.intel file and booted into nvidia and was presented with a black screen. I tried to fix it but ended up with a initramfs screen at some point and decided to reinstall ubuntu entirely again. But I hope this won't happen again.
